import math

from PIL import ImageFont

""" HEXES """
HEX_SIZE = 200 # Less then 100 makes information jumbled
HEX_WIDTH = 2 * HEX_SIZE
HEX_HEIGHT = math.sqrt(3) * HEX_SIZE
HEX_BG = (15, 0, 25)
HEX_OUTLINE = (255, 255, 255)
HEX_THICKNESS = 1

""" DIMENSIONS """
COL_MULTIPLE = 8
ROW_MULTIPLE = 10

""" CANVAS """
CANVAS_BG = (15, 10, 15)

""" FONTS """
FONT_PATH = '/usr/share/fonts/liberation-fonts/LiberationMono-Regular.ttf'
FONT_SIZE_TINY = int(HEX_SIZE * 1/10)
FONT_SIZE_SMALL = int(HEX_SIZE * 9/50)
FONT_SIZE_LARGE = int(HEX_SIZE * 11/50)
FONT_TINY = ImageFont.truetype(FONT_PATH, FONT_SIZE_TINY)
FONT_SMALL = ImageFont.truetype(FONT_PATH, FONT_SIZE_SMALL)
FONT_LARGE = ImageFont.truetype(FONT_PATH, FONT_SIZE_LARGE)
FONT_PADDING = 5

""" PLANETS """
PLANET_SIZE = int(HEX_SIZE * 4/25)
PLANET_COLOR_WET = (0, 255, 255)
PLANET_COLOR_DRY = (255, 255, 255)
COLOR_SHIFT_RANGE = 100
MIDPOINT = (HEX_SIZE - PLANET_SIZE) // 2

""" BASES """
BASE_SIZE = HEX_SIZE // 10
DIAGONAL_BASE_FACTOR = 0.9
CARDINAL_BASE_FACTOR = 1.1
BASE_COLOR_ONE = (255, 255, 255)
BASE_COLOR_TWO = (255, 0, 0)
BASE_COLOR_THREE = (255, 200, 0)

""" TRAVEL ZONES """
ZONE_SIZE = int(HEX_SIZE * 4/5)
ZONE_THICKNESS = int(HEX_SIZE * 2/25)
AMBER_ZONE = (255, 200, 0)
RED_ZONE = (255, 0, 50)

""" TRADE LANES """
TRADE_LANE_COLOR = (0, 155, 70, 170)
TRADE_LANE_THICKNESS = HEX_SIZE // 20
TRADE_DISTANCE_LIMIT = 4
JUMP_2_ROUTE_LIMIT = 2

""" LEGEND """
DIRECTIONS = ['COREWARD', 'TRAILING', 'RIMWARD', 'SPINWARD']
